### ISSUE TITLE
Slow response time?

### ISSUE THREAD

**Issue by DiAvisoo** [pruvious-tutorial/05-blog#1]
Cloned the blog repo to try it out. Looks amazing!

The only problem is that it's extremely slow, unusable even. Clicking on "About" takes about 2 seconds to load and when I click on "Portfolio" it takes like 7 seconds for the page to load.

What's happening? Why is it taking so long and is there any way to remedy this?

I'm on a M2 Mac Studio 68GB RAM so it should be quite snappy running locally :)

**Comment by murisceman** [comment]
That's a bit tricky to answer. Can you inspect the dev tools in your browser to see what is taking so much time to load?

**Comment by DiAvisoo** [comment]
Thanks for the swift reply! I'm in the discord right now as well. I created a screen recording of the issue. Seems like it's originating from redirect in Page.vue in Pruvious when fetching data from localhost.
https://youtu.be/HnnjeBeEFHM

**Comment by DiAvisoo** [comment]
Definitely lagging when retrieving the pages. See image.
![Screenshot 2024-04-26 at 15 14 45](https://github.com/pruvious-tutorial/05-blog/assets/5475897/537d2edd-7c49-4c8c-bf08-6693458463af)

**Comment by DiAvisoo** [comment]
Update. Did a fetch in the console and it took 9 seconds:

> var doIt = async () => {
var time = Date.now();
await fetch(window.location.href);
console.log(Date.now() - time);
}
doIt();

< Promise {status: "pending"}
[Log] 9365

Might not be related to Pruvious but a Nuxt/Vite etc problem?

But then again, fetching the favicon takes 6ms only.


> var doIt = async () => {
var time = Date.now();
var res = await fetch('/uploads/favicon.svg');
console.log(Date.now() - time);
console.log(res);
}
doIt();

< Promise {status: "pending"}
[Log] 6
[Log] Response {type: "basic", url: "http://localhost:3001/uploads/favicon.svg", redirected: false, status: 200, ok: true, …}

**Comment by murisceman** [comment]
Hey, thanks for providing the video. Just to rule out the database, could you confirm that the dashboard is working normally, such as authentication, page listing, editing, etc.

**Comment by DiAvisoo** [comment]
Solved it! I was using node 18. Changing it to 20 solved it, fast as lightning now!
